repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.50.0
  hooks:
    - id: terraform_fmt
    - id: terragrunt_fmt
    - id: terraform_tflint
    - id: terraform_tfsec
    - id: terraform_checkov
    - id: terrascan
    - id: terraform_docs
    - id: terraform_validate