name: Terragrunt Deploy to Azure

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    # environment: DEV
    env:
      ARM_USE_OIDC: true
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Install Terragrunt
        run: |
          curl -Lo terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v0.48.1/terragrunt_linux_amd64
          chmod +x terragrunt
          sudo mv terragrunt /usr/local/bin/

      - name: Azure Login with OIDC
        uses: azure/login@v1
        with:
          client-id: 23965206-f2a6-4723-b674-62a647cb98a5
          tenant-id: 3940b1f0-857e-413b-8e7d-261d0842437d
          subscription-id: 2422817a-728f-4761-bd14-ff8e63d0f45e

      - name: Terragrunt Init and Plan
        run: |
          cd environments/dev
          terragrunt run-all init
          terragrunt run-all plan -out=tfplan
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_USE_OIDC: true

      # - name: Terragrunt Apply
      #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      #   run: |
      #     cd environments/dev
      #     terragrunt run-all apply --terragrunt-non-interactive
      #   env:
      #     ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      #     ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      #     ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      #     ARM_USE_OIDC: true